- targets: ['192.168.51.222:12345']			## target ip
  labels:
    instance: 'Manager'
    hostname: 'Manager'
- targets: ['192.168.52.222:12345']			## target ip
  labels:
    instance: 'monitoring'
    hostname: 'monitoring'