- targets: ['192.168.56.102:12345']			## target ip
  labels:
    instance: 'milano'
    hostname: 'milano'
- targets: ['192.168.56.103:12345']			## target ip
  labels:
    instance: 'roma'
    hostname: 'roma'