- targets: ['192.168.56.11:12345']			## target ip
  labels:
    instance: 'oracle-19c-rac01'

- targets: ['192.168.56.12:12345']			## target ip
  labels:
    instance: 'oracle-19c-rac02'
 
- targets: ['192.168.56.13:12345']			## target ip
  labels:
    instance: 'oracle-19c-rac03'
