#!/bin/bash

# ============================================================
#  Oracle
#  OS   	: OEL 7.9
#  DB 		: Oracle 19C RAC 3 Node
#  backup	: rman
#  User 	: oracle
#
# RMAN > CONFIGURE RETENTION POLICY TO RECOVERY WINDOW OF 3 DAYS;
# RMAN > CONFIGURE DB_UNIQUE_NAME 'ORA19' CONNECT IDENTIFIER 'ORA19';
# RMAN > CONFIGURE SNAPSHOT CONTROLFILE NAME TO '+FRA/ORA19/snapcf_ORA19.f';
# RMAN > CONFIGURE DEVICE TYPE DISK PARALLELISM 3 BACKUP TYPE TO BACKUPSET;
# RMAN > CONFIGURE BACKUP OPTIMIZATION ON;
# 
# 1번노드에서 실행
#
#  0 6 * * * /bin/sh /${PATH}/script.sh
#
# ============================================================
export ORACLE_BASE=/u02/app/oracle
export ORACLE_HOME=$ORACLE_BASE/product/19.3.0/dbhome_1
export ORACLE_SID="ORA191"                                   
export PATH=$ORACLE_HOME/bin:$PATH
export LANG=C

ASM_BACKUP_DIR="+FRA/ORA19/BACKUPSET"

rman target / catalog ruser/ruser@rman_remote << EOF

RUN {

    ALLOCATE CHANNEL ch01 DEVICE TYPE DISK FORMAT '${ASM_BACKUP_DIR}/db_%d_%T_%U';
    ALLOCATE CHANNEL ch02 DEVICE TYPE DISK FORMAT '${ASM_BACKUP_DIR}/db_%d_%T_%U';
    ALLOCATE CHANNEL ch03 DEVICE TYPE DISK FORMAT '${ASM_BACKUP_DIR}/db_%d_%T_%U';
	
	SQL "ALTER SYSTEM ARCHIVE LOG CURRENT";
    BACKUP DATABASE;
	
	SQL "ALTER SYSTEM ARCHIVE LOG CURRENT";
	BACKUP ARCHIVELOG ALL;
	
    RELEASE CHANNEL ch01;
    RELEASE CHANNEL ch02;
    RELEASE CHANNEL ch03;
}

CROSSCHECK BACKUP;
CROSSCHECK ARCHIVELOG ALL;
DELETE NOPROMPT EXPIRED BACKUP;
DELETE NOPROMPT OBSOLETE;     


EOF